# Generated by Django 3.2.5 on 2021-07-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='my_username', max_length=6, verbose_name='username'),
        ),
    ]
