# Generated by Django 3.2.5 on 2021-07-28 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dod', models.DateField(verbose_name='Date Of Delivery')),
                ('tod', models.CharField(choices=[('n', 'No Time Of Day'), ('s', 'Sunrise'), ('b', 'Breakfast'), ('x', 'Morning'), ('y', 'Afternoon'), ('z', 'Evening')], default='n', max_length=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1)], verbose_name='Time Of Day')),
                ('dow', models.CharField(choices=[('su', 'Sunday'), ('mo', 'Monday'), ('tu', 'Tuesday'), ('we', 'Wednesday'), ('th', 'Thursday'), ('fr', 'Friday'), ('sa', 'Saturday')], default='su', max_length=2, verbose_name='Day Of Week')),
                ('title', models.CharField(max_length=64, verbose_name='Document Title')),
                ('descriptor', models.CharField(max_length=120, verbose_name='Descriptor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('cur_assign_id', models.IntegerField(blank=True, null=True, verbose_name='current Assignment ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan', models.CharField(max_length=3, verbose_name='Language')),
                ('tran_title', models.CharField(max_length=70, verbose_name='Translated title')),
                ('descrip', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('blkc', models.IntegerField(verbose_name='Block count')),
                ('subc', models.IntegerField(verbose_name='Sub-block count')),
                ('senc', models.IntegerField(verbose_name='Sentence count')),
                ('xcrip', models.CharField(choices=[('A', 'Andes'), ('M', 'Mamalis')], default='A', max_length=1, verbose_name='Transcription')),
                ('li', models.BooleanField(verbose_name='Lookup imported (eng) / translate contributions randomized (oth)')),
                ('pubdate', models.DateField(verbose_name='Publication date')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tranai.document')),
                ('eng_tran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tranai.translation')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EP', 'English Provider (EP)'), ('EE', 'English Editor (EE)'), ('NT', 'No Translator (NT)'), ('MT', 'Machine Translator (MT)'), ('HT', 'Human Translator (HT)'), ('TE', 'Translation Editor (TE)'), ('SE', 'Scripture Editor (SE)'), ('PE', 'Poetry Editor (PE)'), ('CE', 'Chief Editor (CE)'), ('LA', 'Language Administrator (LA)')], default='TE', max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)], verbose_name='Role')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('place', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Place')),
                ('ci', models.BooleanField(default=False, verbose_name='Content imported')),
                ('status', models.CharField(choices=[('ip', 'In Process (ip)'), ('cd', 'Completed (cd)'), ('te', 'TE editing (te)'), ('ce', 'CE editing (ce)'), ('qe', 'QE editing (qe)'), ('pg', 'Publishing (pg)'), ('pd', 'Published (pd)'), ('pr', 'Pruned (pr)')], default='ip', max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)], verbose_name='Status')),
                ('ccs', models.IntegerField(blank=True, null=True, verbose_name='Final Create additions')),
                ('ccs_k', models.IntegerField(blank=True, null=True, verbose_name='- by klearing')),
                ('ccs_m', models.IntegerField(blank=True, null=True, verbose_name='- by modding')),
                ('vcs', models.IntegerField(blank=True, null=True, verbose_name='Final Vote additions')),
                ('vcs_a', models.IntegerField(blank=True, null=True, verbose_name='- by accepting')),
                ('vcs_c', models.IntegerField(blank=True, null=True, verbose_name='- by creating')),
                ('vcs_t', models.IntegerField(blank=True, null=True, verbose_name='- by topping')),
                ('vcs_p', models.IntegerField(blank=True, null=True, verbose_name='- by picking')),
                ('ct', models.IntegerField(blank=True, null=True, verbose_name='Final Create time (s)')),
                ('vt', models.IntegerField(blank=True, null=True, verbose_name='Final Vote time (s)')),
                ('majtes', models.IntegerField(blank=True, null=True, verbose_name='Final Majority Top Changes')),
                ('tietes', models.IntegerField(blank=True, null=True, verbose_name='Final Tie Top Changes')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Notes')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='tranai.translation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='tranai.user')),
            ],
        ),
    ]
