# Generated by Django 3.2.5 on 2021-07-29 21:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tranai', '0004_auto_20210728_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='pubdate',
            field=models.DateField(default=datetime.date.today, verbose_name='Publication date'),
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blk', models.IntegerField(blank=True, null=True, verbose_name='Block')),
                ('sub', models.IntegerField(blank=True, null=True, verbose_name='Sub-block')),
                ('rsub', models.IntegerField(blank=True, null=True, verbose_name='Running sub-block')),
                ('sen', models.IntegerField(blank=True, null=True, verbose_name='Sentence')),
                ('rsen', models.IntegerField(blank=True, null=True, verbose_name='Running sentence')),
                ('typ', models.IntegerField(blank=True, null=True, verbose_name='Sentence type')),
                ('tie', models.BooleanField(default=False, verbose_name='Tie')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sentences', to='tranai.translation')),
            ],
        ),
    ]
