# Generated by Django 3.2.5 on 2021-08-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tranai', '0007_change'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Change',
        ),
    ]
