# Generated by Django 3.2.5 on 2021-08-02 19:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tranai', '0008_delete_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(1024)], verbose_name='Content')),
                ('hid', models.BooleanField(default=False, verbose_name='Hidden')),
                ('top', models.CharField(choices=[('N', 'No?'), ('Z', 'Zero-vote?'), ('T', 'Tie'), ('M', 'Majority')], default='Z', max_length=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1)], verbose_name='Top Change')),
                ('mods', models.IntegerField(blank=True, null=True, verbose_name='Mods')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='tranai.sentence')),
            ],
        ),
    ]
