# Generated by Django 3.2.5 on 2021-08-02 20:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tranai', '0009_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='top',
            field=models.CharField(choices=[('N', 'Not top change'), ('Z', 'Zero vote top change'), ('T', 'Tie top change'), ('M', 'Majority top change')], default='Z', max_length=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1)], verbose_name='Top Change'),
        ),
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('E', 'English'), ('T', 'Translate'), ('C', 'Create'), ('V', 'Vote')], max_length=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1)], verbose_name='Kind')),
                ('effort_in_seconds', models.IntegerField(blank=True, null=True, verbose_name='Effort in seconds')),
                ('base', models.CharField(choices=[('k', 'clearing'), ('m', 'modding'), ('a', 'accepting'), ('c', 'creating'), ('t', 'topping'), ('p', 'picking another')], max_length=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1)], verbose_name='Base')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tranai.change')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='tranai.change')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='tranai.task')),
            ],
        ),
    ]
