# Generated by Django 3.2.5 on 2021-07-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
